# Generated by Django 4.2 on 2025-12-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('idBarang', models.AutoField(primary_key=True, serialize=False)),
                ('namaBarang', models.CharField(max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
                ('deskripsi', models.CharField(max_length=200)),
                ('ukuran', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_barang/', verbose_name='Foto Produk')),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('idPelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('namaPelanggan', models.CharField(max_length=50)),
                ('noHp', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('idPenyewaan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalPesan', models.DateField(auto_now_add=True)),
                ('tanggalAcara', models.DateField()),
                ('durasiSewa', models.PositiveIntegerField()),
                ('totalBayar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statusSewa', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('alamatPemasangan', models.CharField(max_length=200)),
                ('tanggalPembongkaran', models.DateField()),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan')),
            ],
            options={
                'verbose_name': 'Penyewaan',
                'verbose_name_plural': 'Penyewaan',
            },
        ),
        migrations.CreateModel(
            name='DetailSewa',
            fields=[
                ('idDetailSewa', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahBarang', models.PositiveIntegerField()),
                ('statusBarang', models.CharField(choices=[('Baik', 'Baik'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang')], default='Baik', max_length=20)),
                ('subTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('idBarang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barang')),
                ('idPenyewaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.penyewaan')),
            ],
            options={
                'verbose_name': 'Detail Sewa',
                'verbose_name_plural': 'Detail Sewa',
            },
        ),
    ]
