# Generated by Django 4.2 on 2025-11-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('idBarang', models.AutoField(primary_key=True, serialize=False)),
                ('namaBarang', models.CharField(max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
                ('deskripsi', models.CharField(max_length=200)),
                ('ukuran', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_barang/', verbose_name='Foto Produk')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('idPelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('namaPelanggan', models.CharField(max_length=50)),
                ('noHp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('idPenyewaan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalPesan', models.DateField(auto_now_add=True)),
                ('tanggalAcara', models.DateField()),
                ('durasiSewa', models.PositiveIntegerField()),
                ('totalBayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statusSewa', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('alamatPemasangan', models.CharField(max_length=200)),
                ('tanggalPembongkaran', models.DateField()),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='DetailSewa',
            fields=[
                ('idDetailSewa', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahBarang', models.PositiveIntegerField()),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idBarang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barang')),
                ('idPenyewaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.penyewaan')),
            ],
        ),
    ]
