# Generated by Django 4.2 on 2025-12-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsewa',
            name='jumlahBermasalah',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Rusak/Hilang'),
        ),
    ]
