# Generated by Django 4.2 on 2025-11-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='password',
        ),
    ]
