# Generated by Django 4.2 on 2025-11-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pelanggan_email_remove_pelanggan_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyewaan',
            name='totalBayar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
