# Generated by Django 4.2 on 2025-11-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_penyewaan_totalbayar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name': 'Barang', 'verbose_name_plural': 'Barang'},
        ),
        migrations.AlterModelOptions(
            name='detailsewa',
            options={'verbose_name': 'Detail Sewa', 'verbose_name_plural': 'Detail Sewa'},
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'verbose_name': 'Pelanggan', 'verbose_name_plural': 'Pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='penyewaan',
            options={'verbose_name': 'Penyewaan', 'verbose_name_plural': 'Penyewaan'},
        ),
        migrations.AlterField(
            model_name='detailsewa',
            name='subTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
