# Generated by Django 4.2 on 2025-11-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_barang_options_alter_detailsewa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsewa',
            name='statusBarang',
            field=models.CharField(choices=[('Baik', 'Baik'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang')], default='Baik', max_length=20),
        ),
    ]
