"""
Django settings for PasirMas project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m-pqvg6_^s9e5*r-$%ux*=i39bjw3j^mp9)44ran82wumq=h0n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# settings.py

INSTALLED_APPS = [
    # Tambahkan ini:
    'django_bootstrap5', 
    
    # Aplikasi Pihak Ketiga
    'jazzmin',
    'django_tables2', # Anda mungkin juga memerlukan ini untuk tabel
    'django_filters', # Anda mungkin juga memerlukan ini untuk filter
    
    # Aplikasi Bawaan Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Aplikasi Lokal
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PasirMas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PasirMas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py
# settings.py

JAZZMIN_SETTINGS = {
    # TITLE AND BRANDING
    "site_title": "PasirMas Admin", 
    "site_header": "PasirMas Administration",
    "welcome_sign": "Welcome to PasirMas Admin Panel",
    "site_brand": "Pasir Mas Atambua",
    "copyright": "PasirMas © 2024",
    
    # ICONS
    "icons": {
        "auth": "fas fa-users-cog",
        "core": "fas fa-box-open",
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users",
        "core.pelanggan": "fas fa-user",
        "core.barang": "fas fa-box",
        "core.penyewaan": "fas fa-handshake",
    },
    
    # SIDEBAR
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # =======================================================
    # NAV BAR (USERMENU LINKS) - DROPDOWN LAPORAN (IKON BARU 🔥)
    # =======================================================
    "usermenu_links": [
        # Tautan User default (tetap dipertahankan)
        {"model": "auth.user"},
        
        # 🔥 DROPDOWN KUSTOM LAPORAN DENGAN IKON RELEVAN
        {"name": "Laporan", "icon": "fas fa-chart-pie", "url": "admin:report_penyewaan", "children": [
            # Ikon untuk setiap laporan
            {"name": "Laporan Penyewaan", "url": "admin:report_penyewaan", "icon": "fas fa-file-contract", "new_window": False},
            {"name": "Laporan Keuangan", "url": "admin:report_keuangan", "icon": "fas fa-coins"},
            {"name": "Laporan Status Barang", "url": "admin:report_barang", "icon": "fas fa-boxes"},
            {"name": "Laporan Data Pelanggan", "url": "admin:report_pelanggan", "icon": "fas fa-users-cog"},
        ]},
    ],
    
    # =======================================================
    # SIDEBAR LINKS 
    # =======================================================
    "sidebar_links": [
        # Dashboard
        {"name": "Dashboard", "url": "admin:index", "icon": "fas fa-tachometer-alt"},

        # Pemisah Section: Manajemen Data
        {"section": "Manajemen Data"},
        {"model": "core.Pelanggan", "icon": "fas fa-users"},
        {"model": "core.Barang", "icon": "fas fa-box"},
        {"model": "core.Penyewaan", "icon": "fas fa-handshake"},
        
        # Pemisah Section: Pengaturan Sistem
        {"section": "Pengaturan Sistem"},
        {"app": "auth", "icon": "fas fa-users-cog"}, 
    ],
    
    # Urutan Model (Untuk Halaman Utama Admin)
    "order_with_respect_to": [
        "auth", 
        "core.Pelanggan",
        "core.Barang", 
        "core.Penyewaan",
    ],
    
    # UI Tweaks (opsional)
    "ui_tweaks": {
        "navbar_small": False,
        "sidebar_fixed": True,
        "sidebar_compact": False,
        "sidebar_nav_child_indent": True,
        "sidebar_nav_small_text": False,
        "body_small": False,
        "brand_small": False,
    }
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-warning",
    "accent": "accent-orange",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-warning",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "lumen",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}